language: rust
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.rustup/
    - $HOME/.cargo/

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake # also required for cargo-update
    sources:
      - kalakris-cmake

rust:
  - 1.29.0
  - 1.30.0
  - 1.31.0
  - 1.32.0
  - 1.33.0
  - stable
  - beta
  - nightly

script:
  - cargo clean
  - cargo build --release
  - cargo test --release
  - cargo doc -p pinyin --no-deps
  - cargo run --example main
  - cargo bench
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      # install cargo-travis here to that dependency crates can be cached properly
      cargo install cargo-update || echo "cargo-update already installed"
      cargo install cargo-travis || echo "cargo-travis already installed"
      cargo install-update -a # update outdated cached binaries
    fi

after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo coveralls
    fi

matrix:
  allow_failures:
    - rust: nightly
