language: rust
dist: trusty

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test
  - cargo test --no-default-features --features=plain
  - cargo test --no-default-features --features=with_tone
  - cargo test --no-default-features --features=with_tone_num
  - cargo test --no-default-features --features=with_tone_num_end
  - cargo test --no-default-features --features=plain,heteronym
  - cargo test --no-default-features --features=with_tone,heteronym
  - cargo test --no-default-features --features=with_tone_num,heteronym
  - cargo test --no-default-features --features=with_tone_num_end,heteronym
  - cargo doc

after_success:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
        curl -sL https://github.com/xd009642/tarpaulin/releases/download/0.8.3/cargo-tarpaulin-0.8.3-travis.tar.gz | \
          tar xvz -C $HOME/.cargo/bin
        cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID \
          --exclude-files 'tests/*' --exclude-files 'coverage-check/*'
      fi

matrix:
  allow_failures:
    - rust: nightly
